
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: medusa
          POSTGRES_PASSWORD: medusa
          POSTGRES_DB: medusa
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install root deps (if any)
        run: npm install
      - name: Install backend deps if exists
        run: |
          if [ -d apps/backend ]; then
            cd apps/backend
            npm ci || npm install
          fi
      - name: Build backend
        run: |
          if [ -d apps/backend ]; then
            cd apps/backend
            npx medusa build || npm run build || true
          fi
      - name: Install storefront deps if exists
        run: |
          if [ -d apps/storefront ]; then
            cd apps/storefront
            npm ci || npm install
          fi
      - name: Build storefront
        run: |
          if [ -d apps/storefront ]; then
            cd apps/storefront
            npm run build || true
          fi
